### ISSUE TITLE
更新錯誤 GPIO

### ISSUE THREAD

**Issue by MarcusTseng** [xangin/luta-esp32c3-eink#1]
GPIO的警告導致無法更新
這個就只能丟著不理了吧?...

`WARNING GPIO8 is a strapping PIN and should only be used for I/O with care.
Attaching external pullup/down resistors to strapping pins can cause unexpected failures.
See https://esphome.io/guides/faq.html#why-am-i-getting-a-warning-about-strapping-pins
Failed config

switch.gpio: [source /config/esphome/luat-esp32c3-eink.yaml:94]
  platform: gpio
  name: esp32c3-eink D5 LED
  
  This pin cannot be used on ESP32-C3s and is already used by the SPI/PSRAM interface (function: SPIWP).
  pin: GPIO13
  id: relay`

**Comment by xangin** [comment]
謝謝回報問題，後來找了一下解法
可以在pin的地方加上忽略錯誤的指令即可正常編譯
YAML已同步更新，您再試試看！
 - platform: gpio
    pin: 
      number: GPIO13
      **ignore_pin_validation_error: true**
